global:
  scrape_interval: 5s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 5s # Evaluate rules every 15 seconds. The default is every 1 minute.
  scrape_timeout: 4s

alerting:
  alertmanagers:
  - static_configs:
    - targets: ['cita_monitor_server_alertmanager:9093']

rule_files:
  - 'alert.rules'

scrape_configs:
  - job_name: 'host_exporter'
    static_configs:
    - targets: ['citamon_agent_host_ip:1920']
    metrics_path: "/metrics/host"

  - job_name: 'process_exporter'
    static_configs:
    - targets: ['citamon_agent_host_ip:1920']
    metrics_path: "/metrics/process"

  - job_name: 'rabbitmq_exporter'
    static_configs:
    - targets: ['citamon_agent_host_ip:1920']
    metrics_path: "/metrics/rabbitmq"

  - job_name: 'cita_exporter'
    static_configs:
    - targets: ['citamon_agent_host_ip:1920']
    metrics_path: "/metrics/cita"
