version: '3'
services:
  prometheus:
    user: root
    image: prom/prometheus:v2.6.0
    container_name: cita_monitor_server_prometheus
    hostname: prometheus_server
    privileged: true
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./config/alert.rules:/etc/prometheus/alert.rules
      - ./data:/etc/prometheus/data
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    depends_on:
      - alertmanager
    ports:
      - '${prometheus_HostPort}:${prometheus_ContainerPort}'

  alertmanager:
    image: prom/alertmanager:v0.15.3
    container_name: cita_monitor_server_alertmanager
    hostname: prometheus_alertmanager_server
    volumes:
      - ./config/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
    ports:
      - '${alertmanager_HostPort}:${alertmanager_ContainerPort}'

  grafana:
    user: root
    build: ./grafana
    image: cryptape/grafana:5.4.2
    container_name: cita_monitor_server_grafana
    hostname: grafana_server
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_PATHS_CONFIG=/etc/grafana/grafana.ini
    volumes:
      - ./config/grafana:/etc/grafana
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - ./grafana/grafanadb:/var/lib/grafana/grafanadb
    depends_on:
      - prometheus
    ports:
      - '${grafana_HostPort}:${grafana_ContainerPort}'

volumes:
  grafana_data: {}
  prometheus_data: {}

